# Github Action to lint and test a uv python project 

name: Lint and test (pr)
on:
  pull_request:
    branches:
      - master 

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Setup Virtual Environment and Install Dependencies
        run: |
          uv venv
          . .venv/bin/activate
          uv sync --extra test
          
      - name: Run Linters
        run: |
          . .venv/bin/activate
          uv pip install ruff
          uv pip install mypy
          ruff check .
          mypy src/sat_x tests/

      - name: Run Tests
        run: |
          . .venv/bin/activate
          pytest tests/ -v --cov=sat_x --cov-report=term-missing

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: ignore

